### ISSUE TITLE
Make the build paths in runQMake.bat relative

### ISSUE THREAD

**Issue by Localtings** [MatusGuy/RobloxStudio-DiscordRPC#1]
At first, it was all good, I downloaded the libs from the batch file, and then when I tried to compile it with runQMake.bat, **IT FAILED** and I was like "what the fuck" then I read the output message and I was like "ah." - I realized that the build paths were absolute and not relative... 💀 But I was too lazy to change em' all by myself, so now I'm here writing this Issue with the hope that you would debug the batch script as soon as possible for me (or any other man who fell into the same problem as me).

**Comment by MatusGuy** [comment]
`runQMake.bat` does not build the project. You're looking for [build instructions](../tree/master/doc/BUILD.md).

**Comment by Localtings** [comment]
aight mb bro

**Comment by MatusGuy** [comment]
Were you able to build with no errors? Add an emoji to this comment if yes, reply if no and I will reopen this issue
